Feat: Sensor Regressions
SJVAir/sjvair.com pull request #149
Opened 2023-08-11 00:05 UTC by alexandermccormick

Creates initial support for running linear regressions against multi-sensor monitors.

2023-09-20 17:44 UTC, dmpayton requested changes

2023-09-20 18:20 UTC, alexandermccormick commented on camp/apps/monitors/admin.py
> +        return mark_safe(Template('''
Done...

2023-09-20 18:20 UTC, alexandermccormick commented on camp/apps/qaqc/admin.py
> +            <p class="analysis-chart"
And done!

2023-09-21 19:14 UTC, dmpayton approved these changes

2023-09-21 19:14 UTC, merged